branches:
  only:
  - master
  - dev
language: java
jdk:
- openjdk11
services:
- postgresql
before_install:
- openssl aes-256-cbc -K $encrypted_58a5abdecf96_key -iv $encrypted_58a5abdecf96_iv
  -in application-dev.properties.enc -out application-dev.properties -d
- cd $TRAVIS_BUILD_DIR/src/main/resources
- cd $TRAVIS_BUILD_DIR
install:
- mvn -N io.takari:maven:wrapper
- "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
before_script:
- psql -c 'create database assistantcsgobot;' -U postgres
script:
- mvn clean package
after_success:
- bash <(curl -s https://codecov.io/bash)
