package com.vaoler.assistantcsgobot.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

@Data
@JsonIgnoreProperties
public class TeamTo {

    private Integer dbId;

    @JsonProperty("id")
    @NotNull
    private String apiId;                                       // Team id generated by API
    @NotBlank
    private String name;                                        // Team name

    private String country;                                     // Team country

    @JsonProperty("country_code")
    private String countryCode;                                 // Team country code

    @NotBlank
    private String abbreviation;                                // Team abbreviation

    private String qualifier;
}
