package com.vaoler.assistantcsgobot.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Data;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

@Data
@JsonIgnoreProperties
public class TeamTo {
    @NotNull
    private String id;                                         // Team id generated by API
    @NotBlank
    private String name;                                        // Team name

    private String country;                                     // Team country
    private String countryCode;                                 // Team country code

    @NotBlank
    private String abbreviation;                                // Team abbreviation

}
